server:
  port: 8181

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true # mapping 과정에서 불필요가 있는경우 fail 처리
# Database
  #postgre
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # 쿼리 포멧
        jdbc:
          lob:
            non_contextual_creation: true
#        temp:
#          use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
#JWT
security:
  myKey: test123

#logging
logging:
  level:
    org:
      hibernate:
        sql: debug # 쿼리문
        type:
          descriptor:
            sql:
              BasicBinder: trace # 입력된 값
      springframework:
        security: DEBUG # spring security check